services:

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy

  app:
    container_name: app
    build:
      context: node
    tty: true
    volumes:
      - ./node:/home/node/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0.37-debian
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=node
    volumes:
      - ./.data/db/mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 3
